### PR TITLE
Cwf/add embed post and replies

### PR DESCRIPTION
**Pull request by chrisfarnham**

### CODE REVIEW

**Review by sampsyo — COMMENTED** [review]
This is AWESOME!!! Thanks so much for contributing this! As you say in the README, I can see this being really useful for that blog-comments workflow. :tada:

I pushed a few small changes to the documentation (the README and the homepage), just to make things a little simpler and streamlined.

I just have one comment on the code: the required class name, `mastodon-post-and-replies`, is a little long and wordy. How about just `mastodon-thread`? This nicely generalizes the two use cases (one toot, a toot and its replies, just replies), IMO, and is a little easier to type. :smiley: Otherwise, the code looks great!!

**Comment by chrisfarnham** [comment]
@sampsyo I just saw your comments, sorry for the delayed response. 

> the required class name, mastodon-post-and-replies, is a little long and wordy. How about just mastodon-thread? 

Great suggestion. I'll update my PR soon to switch to `mastodon-thread`. You can look for it in the next day or so.

Thanks for your library and reviewing my small contributions.

**Comment by chrisfarnham** [comment]
The discussed changes (i.e., renaming class to `mastodon-thread`) has been made.

**Review by sampsyo — APPROVED** [review]
Looks absolutely fantastic! Many thanks again!!

**Comment by sampsyo** [comment]
I've release v1.5.0 with this feature.

**Pull request merged**
